/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_Espace_agent (void);
GtkWidget* create_Login (void);
GtkWidget* create_Ajout_client (void);
GtkWidget* create_Modifier_client (void);
GtkWidget* create_profil_agent (void);
GtkWidget* create_Modifier_agent (void);
